expr=additive;
additive=additive plus multiplicative|additive minus multiplicative|multiplicative;
multiplicative=multiplicative star primary|multiplicative slash primary|primary;
primary=number|lparen expr rparen;
number=digit|number digit;
digit=zero|one|two|three|four|five|six|seven|eight|nine;
zero=z;
one=o;
two=t;
three=h;
four=f;
five=v;
six=s;
seven=e;
eight=i;
nine=n;
plus=p;
minus=m;
star=a;
slash=d;
lparen=l;
rparen=r;
z=x;
o=x;
t=x;
h=x;
f=x;
v=x;
s=x;
e=x;
i=x;
n=x;
p=x;
m=x;
a=x;
d=x;
l=x;
r=x;
x=y;
y=x;
